"""Updating the Chat memebrs table adding the cascade delete

Revision ID: 43aac787bf11
Revises: f7e0ea73d2d8
Create Date: 2025-10-14 22:12:59.032576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43aac787bf11'
down_revision: Union[str, Sequence[str], None] = 'f7e0ea73d2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_members', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('FK__chat_memb__user___5535A963'), 'chat_members', type_='foreignkey')
    op.drop_constraint(op.f('FK__chat_memb__chat___5441852A'), 'chat_members', type_='foreignkey')
    op.create_foreign_key(None, 'chat_members', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.drop_constraint(None, 'chat_members', type_='foreignkey')
    op.create_foreign_key(op.f('FK__chat_memb__chat___5441852A'), 'chat_members', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key(op.f('FK__chat_memb__user___5535A963'), 'chat_members', 'users', ['user_id'], ['id'])
    op.alter_column('chat_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chat_members', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
